CREATE TABLE FILME_SERIES (
ID SERIAL PRIMARY KEY,
NOME VARCHAR (255),
TIPO VARCHAR (1),
TEMPORADA INT,
EPISODIO INT);

CREATE TABLE PESSOA (
CPF INT PRIMARY KEY,
NOME VARCHAR (255),
TELEFONE VARCHAR(255),
NASCIMENTO DATE
 )
 
CREATE TABLE ASSISTIDOS (
CPF_PESSOA INT,
ID_FILMES_SERIES INT,
FOREIGN KEY (CPF_PESSOA) REFERENCES PESSOA(CPF),
FOREIGN KEY (ID_FILMES_SERIES) REFERENCES FILME_SERIES(ID),
DATA_ASSISTIDO DATE
)